name:                 pokeguess
version:              0.1.0.0
visibility:           public
id:                   pokeguess-0.1.0.0-inplace
key:                  pokeguess-0.1.0.0-inplace
license:              MIT
maintainer:           gabriel@example.com
author:               Gabriel
synopsis:             A "Who's that Pokémon?" web game built with Scotty
description:
    PokéGuess is a web service built with Haskell and Scotty.
    Players guess Pokémon by silhouette/name, earn points, and build teams.
    Integrates with the PokéAPI for Pokémon data.

category:             Web, Game
abi:                  inplace
exposed:              True
exposed-modules:      Game PokeAPI Score Team
import-dirs:
    /home/gabriel/Projetos/perso-2026a-GabrieldeQuadro/dist-newstyle/build/x86_64-linux/ghc-9.14.1/pokeguess-0.1.0.0/build

library-dirs:
    /home/gabriel/Projetos/perso-2026a-GabrieldeQuadro/dist-newstyle/build/x86_64-linux/ghc-9.14.1/pokeguess-0.1.0.0/build

library-dirs-static:
    /home/gabriel/Projetos/perso-2026a-GabrieldeQuadro/dist-newstyle/build/x86_64-linux/ghc-9.14.1/pokeguess-0.1.0.0/build

dynamic-library-dirs:
    /home/gabriel/Projetos/perso-2026a-GabrieldeQuadro/dist-newstyle/build/x86_64-linux/ghc-9.14.1/pokeguess-0.1.0.0/build

data-dir:             /home/gabriel/Projetos/perso-2026a-GabrieldeQuadro/.
hs-libraries:         HSpokeguess-0.1.0.0-inplace
depends:
    aeson-2.2.4.1-e4c67e7999b13b85442c0e0bd93331314678816447997912acfe9e8117608c09
    base-4.22.0.0-fde1 bytestring-0.12.2.0-3f3f containers-0.8-89c1
    http-client-0.7.19-c9fe7dc3165295b05b312d1b8c88004e25da58145e37c67325a973d79a1211fd
    http-client-tls-0.3.6.4-ab60ab425980be9fbe7cb61c2f77bc63b707633aab547446ca964928faec0ae5
    http-conduit-2.3.9.1-d689eb1f868d0604cb65ae423c5c6c7b992018c4d6aca0fa0a94a144db52fe6d
    random-1.3.1-3f397cc8e2328ae8f81f95255e80b4dfdc79c4b9066a8dd9d0467505832d1abd
    text-2.1.3-2a27

haddock-interfaces:
    /home/gabriel/Projetos/perso-2026a-GabrieldeQuadro/dist-newstyle/build/x86_64-linux/ghc-9.14.1/pokeguess-0.1.0.0/doc/html/pokeguess/pokeguess.haddock

haddock-html:
    /home/gabriel/Projetos/perso-2026a-GabrieldeQuadro/dist-newstyle/build/x86_64-linux/ghc-9.14.1/pokeguess-0.1.0.0/doc/html/pokeguess
